In [1]:
import numpy as np
import math
import random
from sklearn.preprocessing import normalize
from keras.layers import Dense, Concatenate,concatenate,LeakyReLU, Softmax
from keras.models import Sequential, Model
from keras.optimizers import Adam
import itertools
neurons = 4
input_size = 2
output_size = 1
learning_rate = 0.098
def get_weights():
    return [np.random.randn(2,4)][0]

Using TensorFlow backend.


In [ ]:
'''
    def create_weighted_brain(self, layer_0, layer_1, layer_2):
        model = Sequential()
        model.add(Dense(input_size,input_dim=input_size ,weights=[np.array(layer_0),np.zeros(input_size)], activation='relu'))
        model.add(Dense(neurons, weights=[np.array(layer_1),np.zeros(neurons)], activation='relu'))
        model.add(Dense(output_size ,weights=[np.array(layer_2),np.zeros(output_size)]))
        model.compile(loss='mse', optimizer=Adam(lr=learning_rate), metrics=["accuracy"])
        model._make_predict_function()
        return model
'''     

In [2]:
def mix_weights(weights_1, weights_2):
    mixed = []
    for i in range(len(weights_1)):
        temp = normalize( np.dot( weights_1[i].reshape(-1, 1), weights_2[i].reshape(1, -1) ) )
        mixed.append( np.random.choice( temp[0] , 4).tolist() )
    return mixed

In [3]:
def dot_weights(weights_1, weights_2):
    return np.reshape(normalize(np.dot( np.array(weights_1).reshape(-1, 1),np.array(weights_2).reshape(1, -1) ) )[0], weights_1.shape )

In [4]:
def multiply_weights(weights_1, weights_2):
    multiplied = []
    for i in range(len(weights_1)):
        temp = normalize( weights_1[i].reshape(-1, 1) * weights_2[i].reshape(1, -1) )
        multiplied.append( np.random.choice( temp[0] , 4).tolist() )
    return multiplied

In [5]:
def ordered_select_weights(weights_1, weights_2):
    select = []
    N = 0
    for i in range(len(weights_1)):
        N = len(weights_1[i])
        from_which_list = np.random.randint(2, size=N).astype(np.bool)
        select.append(np.choose(from_which_list, [weights_1[i], weights_2[i]]))

    return select

In [6]:
test_model = Sequential()    
test_model.add(Dense(input_size, input_dim=input_size, activation='relu'))
test_model.add(Dense(neurons, activation='relu'))
test_model.add(Dense(output_size))
test_model.compile(loss='mse', optimizer=Adam(lr=learning_rate), metrics=["accuracy"])

test_model_2 = Sequential()    
test_model_2.add(Dense(input_size, input_dim=input_size, activation='relu'))
test_model_2.add(Dense(neurons, activation='relu'))
test_model_2.add(Dense(output_size))
test_model_2.compile(loss='mse', optimizer=Adam(lr=learning_rate), metrics=["accuracy"])

print(select_weights(test_model.layers[1].get_weights()[0], test_model_2.layers[1].get_weights()[0]))

Instructions for updating:
Colocations handled automatically by placer.
[-0.2580316  -0.7717767   0.762609    0.15267467]
[-0.239151    0.87617207  0.35996866 -0.16904688]
[ 0.6209352   0.6732843   0.11689258 -0.31265402]
[-0.8915887  -0.9437809  -0.62613535  0.785527  ]
[array([-0.239151  ,  0.87617207,  0.762609  ,  0.15267467], dtype=float32), array([ 0.6209352 , -0.9437809 , -0.62613535, -0.31265402], dtype=float32)]


In [7]:
model = Sequential()
model.add(Dense(input_size, input_dim=input_size,weights=[np.array(layer_0),np.zeros(input_size)], activation='relu'))
model.add(Dense(neurons, weights=[np.array(layer_1),np.zeros(neurons)], activation='relu'))
model.add(Dense(output_size ,weights=[np.array(layer_2),np.zeros(output_size)]))
model.compile(loss='mse', optimizer=Adam(lr=learning_rate), metrics=["accuracy"])


print(model.layers[0].get_weights())
print(model.layers[1].get_weights())
print(model.layers[2].get_weights())

NameError: name 'layer_0' is not defined

In [ ]:
def breed(father, mother, orig):
    print(select_weights(father,mother))
    
breed(get_weights(),get_weights(),get_weights())

In [ ]:
N=5
X=20

parent1 = np.random.choice(X, N, replace=True)
parent2 = np.random.choice(X, N, replace=True)

from_which_list = np.random.randint(2, size=N).astype(np.bool)
selected = np.choose(from_which_list, [parent1, parent2])
